### ISSUE TITLE
TypeInChat -> Syntax Error

### ISSUE THREAD

**Issue by Mocca55** [HGIC/StreamScripts#1]
Hallo the TypeInChat has an SyntaxError here are the Pyhton Log.

Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> TypeInChat.py -t "Kappa"
  File "<stdin>", line 1
    TypeInChat.py -t "Kappa"
                     ^
SyntaxError: invalid syntax
>>>

**Comment by Mocca55** [comment]
I have fixed the Problem with -> python -> pip install pytwitchapi
and the following code


```
# Config portion
import socket
import sys
import getopt


def main(argv):
    texttotype = ' '
    try:
      opts, args = getopt.getopt(argv,"t:u:")
    except getopt.GetoptError:
      print ('Failed')
      sys.exit(2)
      
    for opt, arg in opts:
      if opt in ("-t"):
        texttotype = arg
      else:
        sys.exit(2)
    
    NICK = "nick"  # your twitch username, lowercase
    PASS = "oauth:accestoken"  #include oauth: -> Enter access token that is generated from twitchtokengenerator.com
    
    HOST = "irc.chat.twitch.tv"  # the twitch irc server
    PORT = 6667  # always use port 6667
    CHAN = "#channelname"  # your twitch channel name must include #

    
    s = socket.socket()
    s.connect((HOST, PORT))
    s.send(bytes('PASS ' + PASS + '\r\n', 'utf-8'))
    s.send(bytes('NICK ' + NICK + '\r\n', 'utf-8'))
    s.send(bytes('JOIN ' + CHAN + '\r\n', 'utf-8'))

    s.send(bytes('PRIVMSG ' + CHAN + ' :' + texttotype + '\r\n', 'utf-8'))

if __name__ == "__main__":
    main(sys.argv[1:])
```

**Comment by HGIC** [comment]
Sorry for the delay in my response. I don't see where pytwitchapt helped this problem as it is not included in the script. It seems that, based on your comment in the code that you may not have had oauth: in your token. I don't have pytwitchapt installed on any of the machines that I tested on.

**Comment by Mocca55** [comment]
Hallo no Problem for the delay.

I have Chance the Acces Thoken with
oauth: befor the Acces Token

and the 
else -> else:

Can you Test this in your machines without pytwitchapi?

Greetings Mocca55
